server {

    listen 127.0.0.1:80;
    server_name ci4;

    # -------------------------
    # Security headers
    # -------------------------
    add_header Strict-Transport-Security "max-age=3600" always;

    # -------------------------
    # Document root
    # -------------------------
    root /var/www/ci4/userguide/docs;
    index index.html index.php;

    # -------------------------
    # Routing
    # -------------------------
    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }
}
